### ISSUE TITLE
Are you allowed to post Heckendorn's Matrix class?

### ISSUE THREAD

**Issue by iicurtis** [GhostofGoes/cgoes-cs404#1]
Just being pedantic as I casually browse through random other people's githubs. I was thinking about posting my solutions to the course as well from a few years ago. 

Are we allowed to redistribute Heckendorn's matrix class? I see that you have it distributed under matv2/mat.*

Edit:
RIP - I noticed you reproduced your own with similar functionality.

**Comment by GhostofGoes** [comment]
Going to be safe and say "no, you can't". 

Yeah, as you noticed, I wrote my own matrix library...don't use it, it's terrible and buggy.
